const CATS=["efemerides","comunicados","discursos","correos","derechos_peticion","tweets","institucional","parrillas","efemerides_academicas","otros"];
const INST_HEADER='Rectoría | Universidad Nacional de Colombia'; const INST_FOOT='Carrera 45 # 26-85';
const dec=(s)=>decodeURIComponent(escape(atob(s))).split('').map((c,i)=>String.fromCharCode(c.charCodeAt(0)^((i%7)+3))).join('');
const sha=async(t)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t)))).map(x=>x.toString(16).padStart(2,'0')).join('');
(async()=>{const stored=localStorage.getItem('admin_hash')||await sha('UNAL-Rector-Admin-2026'); if(!localStorage.getItem('admin_hash')) localStorage.setItem('admin_hash',stored); cat.innerHTML=CATS.map(c=>`<option>${c}</option>`).join('');
loginBtn.onclick=async()=>{if(await sha(pwd.value)===localStorage.getItem('admin_hash')){loginView.style.display='none';panel.style.display='block';load();}else alert('Contraseña inválida');};})();
async function load(){let all=[];for(const c of CATS){const docs=await fetch(`../${c}/metadata.json`).then(r=>r.json()).catch(()=>[]);const t=new Date();const v=docs.filter(d=>new Date(d.fecha_limite)<t).length;const p=docs.filter(d=>{const diff=(new Date(d.fecha_limite)-t)/86400000;return diff>=0&&diff<=7}).length;adminCards.innerHTML+=`<div class='card'><h3>${c}</h3><p>${docs.length} docs</p><p>🟡${p} 🔴${v}</p></div>`;all=all.concat(docs.map(d=>({...d,categoria:c})));}
renderTable(all)}
function renderTable(rows){tabla.innerHTML='<table><tr><th>Archivo</th><th>Título</th><th>Palabras</th><th>Fecha</th><th>Estado</th><th>Acciones</th></tr>'+rows.map(r=>`<tr><td>${r.archivo}</td><td contenteditable onblur="upd('${r.categoria}','${r.archivo}','titulo',this.innerText)">${r.titulo}</td><td contenteditable onblur="upd('${r.categoria}','${r.archivo}','palabras',this.innerText)">${r.palabras}</td><td contenteditable onblur="upd('${r.categoria}','${r.archivo}','fecha_limite',this.innerText)">${r.fecha_limite}</td><td><select onchange="upd('${r.categoria}','${r.archivo}','estado',this.value)"><option ${r.estado==='pendiente'?'selected':''}>pendiente</option><option ${r.estado==='en revisión'?'selected':''}>en revisión</option><option ${r.estado==='aprobado'?'selected':''}>aprobado</option><option ${r.estado==='vencido'?'selected':''}>vencido</option></select></td><td><button onclick="replaceDoc('${r.categoria}','${r.archivo}')">Reemplazar</button><button onclick="delDoc('${r.categoria}','${r.archivo}')">Eliminar</button><a href='../editor.html?cat=${r.categoria}&file=${encodeURIComponent(r.archivo)}'>Ver</a></td></tr>`).join('')+'</table>';}
subir.onclick=async()=>{const f=file.files[0]; if(!f) return alert('Seleccione archivo');const meta={archivo:f.name,titulo:titulo.value,categoria:cat.value,palabras:+palabras.value,fecha_limite:fecha.value,estado:estado.value,medio:medio.value,encabezado:enc.checked,pie_pagina:pie.checked,actualizado:new Date().toISOString().slice(0,10)};if(!meta.encabezado||!meta.pie_pagina) alert('Advertencia: faltan marcadores institucionales.'); await ghUpsert(cat.value,f.name,await fileToB64(f),`Sube ${f.name}`); const arr=await fetch(`../${cat.value}/metadata.json`).then(r=>r.json());arr.push(meta);await saveMetadata(cat.value,arr,`Actualiza metadata ${cat.value}`);alert('Subido');location.reload();}
async function upd(cat,file,key,val){const arr=await fetch(`../${cat}/metadata.json`).then(r=>r.json());const i=arr.findIndex(x=>x.archivo===file);arr[i][key]=key==='palabras'?+val:val;arr[i].actualizado=new Date().toISOString().slice(0,10);if(new Date(arr[i].fecha_limite)<new Date())arr[i].estado='vencido';await saveMetadata(cat,arr,`Edita metadata ${file}`)}
async function delDoc(cat,file){if(!confirm('¿Eliminar documento y metadata?')) return;await ghDelete(`${cat}/${file}`,`Elimina ${file}`);const arr=await fetch(`../${cat}/metadata.json`).then(r=>r.json());await saveMetadata(cat,arr.filter(x=>x.archivo!==file),`Elimina metadata ${file}`);location.reload();}
async function replaceDoc(cat,file){const inp=document.createElement('input');inp.type='file';inp.accept='.docx';inp.onchange=async()=>{const f=inp.files[0];const txt=await f.text();if(!txt.includes(INST_HEADER)||!txt.includes(INST_FOOT)) alert('Advertencia: el archivo no contiene encabezado/pie institucional en texto detectable.');await ghUpsert(cat,file,await fileToB64(f),`Reemplaza ${file}`);const arr=await fetch(`../${cat}/metadata.json`).then(r=>r.json());const i=arr.findIndex(x=>x.archivo===file);arr[i].actualizado=new Date().toISOString().slice(0,10);await saveMetadata(cat,arr,`Actualiza fecha ${file}`);alert('Reemplazado');location.reload();};inp.click();}
async function fileToB64(f){return btoa(String.fromCharCode(...new Uint8Array(await f.arrayBuffer())))}
async function ghReq(path,method,body){const cfg=JSON.parse(localStorage.getItem('gh_cfg')||'{}');const token=dec(cfg.token||'');const res=await fetch(`https://api.github.com/repos/${cfg.owner}/${cfg.repo}/contents/${path}`,{method,headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json'},body: body?JSON.stringify(body):undefined});if(!res.ok)throw new Error(await res.text());return res.json();}
async function ghUpsert(cat,name,b64,msg){let sha;try{sha=(await ghReq(`${cat}/${name}`,'GET')).sha}catch{};const cfg=JSON.parse(localStorage.getItem('gh_cfg')||'{}');return ghReq(`${cat}/${name}`,'PUT',{message:msg,content:b64,branch:cfg.branch||'main',sha});}
async function ghDelete(path,msg){const cfg=JSON.parse(localStorage.getItem('gh_cfg')||'{}');const f=await ghReq(path,'GET');return ghReq(path,'DELETE',{message:msg,sha:f.sha,branch:cfg.branch||'main'});}
async function saveMetadata(cat,obj,msg){await ghUpsert(cat,'metadata.json',btoa(unescape(encodeURIComponent(JSON.stringify(obj,null,2)))),msg)}
